### ISSUE TITLE
Lab records export includes un-obfuscated data

### ISSUE THREAD

**Issue by mmuller** [instedd/maap-collector#108]
File: https://maap-stg.instedd.org/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBRZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2f8b83ba3ace9288aaf64252c57e34e305332f14/Download.xls?disposition=attachment

**Comment by hdf1986** [comment]
Closed since it's an expected behaviour.

Some rows in the export are un-obfuscated because the selected `data_rows_to` was 22 instead of 33 (which decides to obfuscate and use until row 22 instead of 33)
![image](https://user-images.githubusercontent.com/1130309/63617847-ebaeb980-c5c0-11e9-84d5-b35a48b80011.png)
